[build]
  base    = "frontend"
  publish = "dist" # This path is relative to the 'base' directory
  command = "npm install && npm run build" # This command is executed in the 'base' directory

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
